name: Add votes to issue
on:
  issues:
    types:
      - opened
jobs:
  add_emoji:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (if needed)
        uses: actions/checkout@v4

      - name: Add ğŸ‘ and ğŸ‘ reaction to the issue
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_URL: ${{ github.event.issue.url }}
        run: |
          set +e
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            $ISSUE_URL/reactions \
            -f 'content=+1' >/dev/null
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            $ISSUE_URL/reactions \
            -f 'content=-1' >/dev/null
          set -e