name: Add votes to issue
on:
  issues:
    types:
      - opened
jobs:
  add_emoji:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (if needed)
        uses: actions/checkout@v4

      - name: Add ðŸ‘ and ðŸ‘Ž reaction to the issue
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_URL: ${{ github.event.issue.url }}
        run: |
          set +e

          echo "Add ðŸ‘"
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            $ISSUE_URL/reactions \
            -f 'content=+1' >/dev/null

          echo "Add ðŸ‘Ž"
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            $ISSUE_URL/reactions \
            -f 'content=-1' >/dev/null

          set -e

  add_labels:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (if needed)
        uses: actions/checkout@v4

      - name: Add labels
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_URL: ${{ github.event.issue.number }}
          GH_ASSIGNED_TO: FlizzerMDX # ${{github.actor}}
        run: |
          set +e

          echo "Get title of the issue"
          title=$(gh issue view $ISSUE_URL --json title)

          echo "Get body of the issue"
          body=$(gh issue view $ISSUE_URL --json body)

          if [[ ${title,,} = *"docs"* ]] || [[ ${title,,} = *"documentation"* ]] || \
          [[ ${body,,} = *"docs"* ]] || [[ ${body,,} = *"documentation"* ]]; then
            echo "Add documentation tag"
            gh issue edit $ISSUE_URL --add-label "documentation"
          fi

          set -e

  assign_me:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (if needed)
        uses: actions/checkout@v4

      - name: Assign me to the issue
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_URL: /repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/assignees
          GH_ASSIGNED_TO: FlizzerMDX # ${{github.actor}}
        run: |
          set +e

          echo "Add issue actor to assignees list if missing"
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            $ISSUE_URL/assignees \
            --input - <<< '{
            "assignees": [
              "$GH_ASSIGNED_TO"
            ]}' >/dev/null

          set -e