name: Add votes to issue
on:
  issues:
    types:
      - opened
jobs:
  add_emoji:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (if needed)
        uses: actions/checkout@v4

      - name: Add ðŸ‘ and ðŸ‘Ž reaction to the issue
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ github.event.issue.url }}
        run: |
          set +e

          echo "Add ðŸ‘"
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            $ISSUE_NUMBER/reactions \
            -f 'content=+1' >/dev/null

          echo "Add ðŸ‘Ž"
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            $ISSUE_NUMBER/reactions \
            -f 'content=-1' >/dev/null

          set -e

  add_labels:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (if needed)
        uses: actions/checkout@v4

      - name: Add labels
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          GH_ASSIGNED_TO: FlizzerMDX # ${{github.actor}}
        run: |
          echo "Get title of the issue"
          title=$(gh issue view $ISSUE_NUMBER --json title | tr '[:upper:]' '[:lower:])

          echo "Get body of the issue"
          body=$(gh issue view $ISSUE_NUMBER --json body | tr '[:upper:]' '[:lower:])

          if [[ ${title,,} = *"docs"* ]] || [[ ${title,,} = *"documentation"* ]] || \
          [[ ${body,,} = *"docs"* ]] || [[ ${body,,} = *"documentation"* ]]; then
            echo "Add documentation tag"
            gh issue edit $ISSUE_NUMBER --add-label "documentation"
          fi

          if [[ ${title,,} = *"error"* ]] || [[ ${title,,} = *"bug"* ]] || [[ ${title,,} = *"glitch"* ]] || \
          [[ ${body,,} = *"error"* ]] || [[ ${body,,} = *"bug"* ]] || [[ ${body,,} = *"glitch"* ]]; then
            echo "Add bug tag"
            gh issue edit $ISSUE_NUMBER --add-label "bug"
          fi

          if [[ ${title,,} = *"backend"* ]] || [[ ${title,,} = *"api"* ]] || [[ ${title,,} = *"server"* ]] || [[ ${title,,} = *"back-end"* ]] || \
          [[ ${body,,} = *"backend"* ]] || [[ ${body,,} = *"api"* ]] || [[ ${body,,} = *"server"* ]] || [[ ${body,,} = *"back-end"* ]]; then
            echo "Add API tag"
            gh issue edit $ISSUE_NUMBER --add-label "API"
          fi

          if [[ ${title,,} = *"page"* ]] || [[ ${title,,} = *"frontend"* ]] || [[ ${title,,} = *"ui"* ]] || [[ ${title,,} = *"ux"* ]] || [[ ${title,,} = *"front-end"* ]] || \
          [[ ${body,,} = *"page"* ]] || [[ ${body,,} = *"frontend"* ]] || [[ ${body,,} = *"ui"* ]] || [[ ${body,,} = *"ux"* ]] || [[ ${body,,} = *"front-end"* ]]; then
            echo "Add frontend tag"
            gh issue edit $ISSUE_NUMBER --add-label "Frontend"
          fi